-- Compatibilidad entre la Delivery API (Java) y el esquema restaurado.
-- Ejecuta este script sobre la misma base de datos usada por la app movil/web.

BEGIN;

-- 1) El repositorio Java usa INSERT ... ON CONFLICT (id_usuario) sobre ubicaciones,
--    por lo que id_usuario debe tener una restriccion unica.
ALTER TABLE public.ubicaciones
    ADD CONSTRAINT ubicaciones_id_usuario_key UNIQUE (id_usuario);

-- 2) MensajeRepository solo inserta id_pedido, id_remitente y mensaje.
--    Permitimos que id_destinatario quede nulo para evitar fallos por restricciones.
ALTER TABLE public.mensajes
    ALTER COLUMN id_destinatario DROP NOT NULL;

-- 3) Endpoints de chat esperan tablas chat_conversaciones y chat_mensajes.
CREATE TABLE IF NOT EXISTS public.chat_conversaciones (
    id_conversacion BIGINT PRIMARY KEY,
    id_pedido INTEGER REFERENCES public.pedidos(id_pedido) ON DELETE SET NULL,
    id_cliente INTEGER REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL,
    id_delivery INTEGER REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL,
    id_admin_soporte INTEGER REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL,
    fecha_creacion TIMESTAMPTZ DEFAULT NOW(),
    activa BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.chat_mensajes (
    id_mensaje BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_conversacion BIGINT NOT NULL REFERENCES public.chat_conversaciones(id_conversacion) ON DELETE CASCADE,
    id_remitente INTEGER NOT NULL REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE,
    id_destinatario INTEGER REFERENCES public.usuarios(id_usuario) ON DELETE SET NULL,
    mensaje TEXT NOT NULL,
    fecha_envio TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_mensajes_conversacion
    ON public.chat_mensajes (id_conversacion);

-- 4) Usuario sistema que representa al chatbot (evita depender de personal de soporte).
INSERT INTO public.usuarios (nombre, correo, contrasena, rol, telefono)
VALUES ('Asistente Virtual', 'chatbot@system.local', 'chatbot123', 'soporte', '0000000000')
ON CONFLICT (correo) DO NOTHING;

COMMIT;
