name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  postgres: ^3.5.8
  http: ^1.5.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  intl: ^0.20.2
  location: ^8.0.1
  open_route_service: ^1.2.7
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_rating_bar: ^4.0.1
  permission_handler: ^12.0.1
  carousel_slider: ^5.1.1
  logger: ^2.0.2
  google_maps_flutter: ^2.0.0
  badges: ^3.1.2
  # CORRECCIÓN: Se usa la versión correcta del paquete.
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  lints: ^6.0.0

flutter:
  uses-material-design: true
